from automation.config.config import (
    PROJECT_ROOT, AUTOMATION_DIR, BASE_DIR,
    REPORTS_DIR, SCREENSHOTS_DIR, LOGS_DIR, DATA_DIR,
    TEST_RESULTS_DIR, EXCEL_RESULTS_DIR, HTML_RESULTS_DIR,
    SCREENSHOT_RESULTS_DIR, LOGS_RESULTS_DIR, JSON_RESULTS_DIR, SUMMARY_RESULTS_DIR,
    BASE_URL, BROWSER, HEADLESS, IMPLICIT_WAIT, PAGE_LOAD_TIMEOUT, EXPLICIT_WAIT,
    RETRY_COUNT, SCREENSHOT_ON_FAILURE, LOG_LEVEL, PARALLEL_WORKERS,
    PASS_PERCENT_THRESHOLD, MAX_CRITICAL_FAILURE_PERCENT,
)
