from .base_page import BasePage
from .login_page import LoginPage
from .register_page import RegisterPage
from .forgot_password_page import ForgotPasswordPage
from .dashboard_page import DashboardPage
from .scan_page import ScanPage
from .library_page import LibraryPage
from .tips_page import TipsPage
from .history_page import HistoryPage
from .profile_page import ProfilePage
from .admin_page import AdminPage

# Appium Mobile Pages
from .appium_base_page import AppiumBasePage
from .appium_auth_page import AppiumAuthPage
from .appium_dashboard_page import AppiumDashboardPage
from .appium_scan_page import AppiumScanPage
from .appium_profile_page import AppiumProfilePage
from .appium_library_page import AppiumLibraryPage
from .appium_notifications_page import AppiumNotificationsPage
from .appium_forms_page import AppiumFormsPage
from .appium_navigation_page import AppiumNavigationPage
from .appium_admin_page import AppiumAdminPage
