from .base_page import BasePage
from .login_page import LoginPage
from .register_page import RegisterPage
from .forgot_password_page import ForgotPasswordPage
from .dashboard_page import DashboardPage
from .scan_page import ScanPage
from .library_page import LibraryPage
from .tips_page import TipsPage
from .history_page import HistoryPage
from .profile_page import ProfilePage
from .admin_page import AdminPage
